export const EMAIL_CHANGED = 'sdfd sdl';
export const PASSWORD_CHANGED = '515xc';
export const LOGIN_USER_SUCCESS = '2s1d1f';
export const LOGIN_USER_FAILED = 'jnd';
export const LOGIN_USER = '151d';
export const UPDATE_EMPLOYEE = '129nsk';
export const CREATE_EMPLOYEE = 'kkas s9';
export const EMPLOYEES_FETCH_SUCCESS = 'jnsj skjhna';
export const EMPLOYEE_UPDATE_SUCCESS = 'jns osjkj';